# Official framework image.
# https://hub.docker.com/r/library/node/tags/
# lts = Long Term Support
image: node:lts

services:
  - postgres

variables:
  PIPELINE: true
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  # MASTER_SECRET: not-a-very-secret-secret
  GOOGLE_ID: ${GOOGLE_ID}
  GOOGLE_SECRET: ${GOOGLE_SECRET}
  NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
stages:
  - quality
  - build
  - test
  - deploy

lint:
  stage: quality 
  script:
    - npm run installs
    - npm run lint

build:
  stage: build
  script:
    - npm run installs
    - npm run build

test:
  stage: test
  script:
    - npm run installs
    - npm test

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production