# Official framework image.
# https://hub.docker.com/r/library/node/tags/
# lts = Long Term Support
image: node:lts

services:
  - postgres

variables:
  PIPELINE: true
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  # MASTER_SECRET: not-a-very-secret-secret
  NEXT_PUBLIC_GOOGLE_ID: ${NEXT_PUBLIC_GOOGLE_ID}
  NEXT_PUBLIC_GOOGLE_SECRET: ${NEXT_PUBLIC_GOOGLE_SECRET}
  NEXT_PUBLIC_FACEBOOK_CLIENT_ID: ${NEXT_PUBLIC_FACEBOOK_CLIENT_ID}
  NEXT_PUBLIC_FACEBOOK_SECRET: ${NEXT_PUBLIC_FACEBOOK_SECRET}
  NEXT_PUBLIC_GITHUB_ID: ${NEXT_PUBLIC_GITHUB_ID}
  NEXT_PUBLIC_GITHUB_SECRET: ${NEXT_PUBLIC_GITHUB_SECRET}
  NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}

stages:
  - quality
  - build
  - test
  - deploy

# .test_template: &test_template
#   stage: test
#   before_script:
#     - npm installs

lint:adminService:
  stage: quality
  script:
    - npm install-adminService
    - npm lint-adminService
  rules:
    - changes: 
      - microservices/AdminService/**/*
      - package.json
      - .gitlab-ci.yml

lint:authService:
  stage: quality
  script:
    - npm install-auth
    - npm lint-auth
  rules:
    - changes: 
      - microservices/AuthService/**/*
      - package.json
      - .gitlab-ci.yml
# Add Other Services

lint:enforcement:
  stage: quality
  script:
    - cd app/enforcement && npm install && npm run lint
  rules:
    - changes: 
      - app/enforcement/**/*
      - package.json
      - .gitlab-ci.yml

lint:admin:
  stage: quality
  script:
    - cd app/admin && npm install && npm run lint
  rules:
    - changes: 
      - app/admin/**/*
      - package.json
      - .gitlab-ci.yml

lint:driver:
  stage: quality
  script:
    - cd app/driver && npm install && npm run lint
  rules:
    - changes: 
      - app/driver/**/*
      - package.json
      - .gitlab-ci.yml

# lint:
#   stage: quality 
#   script:
#     - npm run installs
#     - npm run lint



build:
  stage: build
  script:
    - npm run installs
    - npm run build

# Uncomment this @Yaquob
# test:enforcement:
#   script:
#     - cd app/enforcement && npm install && npm test
#   rules:
#     - changes: 
#       - app/enforcement/**/*
#       - package.json
#       - .gitlab-ci.yml

test:admin:
  script:
    - cd app/admin && npm install && npm test
  rules:
    - changes: 
      - app/admin/**/*
      - package.json
      - .gitlab-ci.yml

test:driver:
  script:
    - cd app/driver && npm install && npm test
  rules:
    - changes: 
      - app/driver/**/*
      - package.json
      - .gitlab-ci.yml

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production