services:
  app:
    container_name: app
    profiles:
      - prod
    env_file: .env
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3009:3009"
      - "3011:3011"
      - "3012:3012"
      - "3013:3013"
      - "8080:8080"
    networks:
      - external-network

networks:
  external-network:
    external: true
    name: external-network