FROM node:23-alpine
EXPOSE 8080
EXPOSE 3000
EXPOSE 3001
EXPOSE 3002
EXPOSE 3009

WORKDIR /home/app

COPY ./package.json /home/app/
COPY ./package-lock.json /home/app/
COPY ./.env /home/app/
COPY ./docker-compose.yml /home/app/

# Copy the marketing app
COPY app/marketing/.next/ /home/app/marketing/.next/
COPY app/marketing/public/ /home/app/marketing/public/
COPY app/marketing/.env /home/app/marketing/.env
COPY app/marketing/package.json /home/app/marketing/package.json
COPY app/marketing/package-lock.json /home/app/marketing/package-lock.json
COPY app/marketing/next.config.js /home/app/marketing/next.config.js

# Copy the helloworld app
COPY app/helloworld/.next/ /home/app/helloworld/.next/
COPY app/helloworld/next.config.ts /home/app/helloworld/next.config.ts
COPY app/helloworld/public/ /home/app/helloworld/public/
COPY app/helloworld/package.json /home/app/helloworld/package.json
COPY app/helloworld/package-lock.json /home/app/helloworld/package-lock.json

# Copy the driver app
COPY app/driver/.next/ /home/app/driver/.next/
COPY app/driver/public/ /home/app/driver/public/
COPY app/driver/messages/ /home/app/driver/messages/
COPY app/driver/package.json /home/app/driver/package.json
COPY app/driver/package-lock.json /home/app/driver/package-lock.json
COPY app/driver/next.config.js /home/app/driver/next.config.js
COPY app/driver/.env /home/app/driver/.env

# Copy the admin app
COPY app/admin/.next/ /home/app/admin/.next/
COPY app/admin/public/ /home/app/admin/public/
COPY app/admin/package.json /home/app/admin/package.json
COPY app/admin/package-lock.json /home/app/admin/package-lock.json
COPY app/admin/next.config.js /home/app/admin/next.config.js

# Copy the enforcement app
COPY app/enforcement/.next/ /home/app/enforcement/.next/
COPY app/enforcement/public/ /home/app/enforcement/public/
COPY app/enforcement/package.json /home/app/enforcement/package.json
COPY app/enforcement/package-lock.json /home/app/enforcement/package-lock.json
COPY app/enforcement/next.config.js /home/app/enforcement/next.config.js

# Copy Admin microservice
COPY microservice/AdminService/sql/ /home/app/microservice/AdminService/sql/
COPY microservice/AdminService/build/ /home/app/microservice/AdminService/build/
COPY microservice/AdminService/package.json /home/app/microservice/AdminService/package.json
COPY microservice/AdminService/package-lock.json /home/app/microservice/AdminService/package-lock.json

# Copy Auth microservice
COPY microservice/AuthService/sql/ /home/app/microservice/AuthService/sql/
COPY microservice/AuthService/build/ /home/app/microservice/AuthService/build/
COPY microservice/AuthService/package.json /home/app/microservice/AuthService/package.json
COPY microservice/AuthService/package-lock.json /home/app/microservice/AuthService/package-lock.json

# Copy Permit microservice
COPY microservice/PermitService/sql/ /home/app/microservice/PermitService/sql/
COPY microservice/PermitService/build/ /home/app/microservice/PermitService/build/
COPY microservice/PermitService/package.json /home/app/microservice/PermitService/package.json
COPY microservice/PermitService/package-lock.json /home/app/microservice/PermitService/package-lock.json

# Copy Ticket microservice
COPY microservice/TicketService/sql/ /home/app/microservice/TicketService/sql/
COPY microservice/TicketService/build/ /home/app/microservice/TicketService/build/
COPY microservice/TicketService/package.json /home/app/microservice/TicketService/package.json
COPY microservice/TicketService/package-lock.json /home/app/microservice/TicketService/package-lock.json

# Copy Vehicle microservice
COPY microservice/VehicleService/sql/ /home/app/microservice/VehicleService/sql/
COPY microservice/VehicleService/build/ /home/app/microservice/VehicleService/build/
COPY microservice/VehicleService/package.json /home/app/microservice/VehicleService/package.json
COPY microservice/VehicleService/package-lock.json /home/app/microservice/VehicleService/package-lock.json

RUN npm run cis
CMD ["npm", "start"]