----- DO NOT CHANGE ANYTHING IN THIS FILE ------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE DATABASE auth;

\connect auth;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

----- DO NOT CHANGE ANYTHING IN THIS FILE ------